base_url = "https://zjom.github.io/still"
title = "still"
description = "a minimal Zola theme focused on reading and writing."
author = "still demo"
compile_sass = true
build_search_index = false
generate_feeds = true
feed_filenames = ["atom.xml"]
default_language = "en"

[extra]
still_date_format = "%Y-%m-%d"
still_show_author = true
