name = "still"
description = "a minimal zola blog theme focused on reading and writing"
license = "MIT"
homepage = "https://github.com/zjom/still"
# The minimum version of Zola required
min_version = "0.22.0"
# An optional live demo URL
demo = "https://zjom.github.io/still"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
still_date_format = "%Y-%m-%d"
still_show_author = true

# The theme author info: you!
[author]
name = "Zihan Jin"
homepage = "https://zihanjin.com"
